### PR TITLE
Chrome drivers 115+

### PR DESCRIPTION
**Pull request by gitgrimbo**
Using the work of https://github.com/theintern/digdug/pull/104, but allowing the Chrome driver to use either old or new `baseUrl` for downloads.

### CODE REVIEW

**Comment by jason0x43** [comment]
I like that this one maintains backwards compatibility. @rhpijnacker-philips, does this work for your use case?

**Comment by rhpijnacker-philips** [comment]
Yes, that should be fine. Better even.

**Comment by rhpijnacker-philips** [comment]
@jason0x43 Do you think this has any chance of being released at some point?

**Comment by jason0x43** [comment]
Yes, in the next day or two.

**Pull request merged**
