### PR TITLE
Added support for version ranges

### PR DESCRIPTION
**Pull request by devpaul**
Implements #20 

Take a version string which may contain a range or version aliases and returns a list of individual version for use with the tunnel service

Supported version types and ranges:

 * single version: 9
 * ranged version: 9..11
 * latest keyword: latest
 * previous keyword: previous
 * ranged version with alias: 9..latest
 * mathed version alias: latest-2
 * ranged mathed version alias: latest-2...latest

### CODE REVIEW

**Comment by jason0x43** [comment]
I like where this is going, but I think any environment-specific code should end up in the individual tunnels (i.e., `Tunnel.js` shouldn't have to pick between `environment.browser_version`, `environment.version`, or `environment.short_version`). One way to handle this would be to have the tunnel subclasses parse their own responses rather than trying to have Tunnel do it for everyone. The tunnels could return a list of standardized version items, maybe like:

```js
{
    browserName: 'whatever',
    browser_version: 'whatever',
    platform: 'something',
    platform_version: 'something',
    descriptor: { /* the original service's version object */ }
}
```

`Tunnel.js` would still handle selecting which specific versions to use, but it wouldn't have to worry about service-specific property names, or non-numeric versions (the individual tunnels could filter those out of the returned versions list). It would pass the list of environment objects back to the specific tunnel class, and that class would handle creating Doing this could also help out in the future if we pursue a standardize browser/platform lexicon (since individual tunnels could do name translation before handing the list back to `Tunnel.js`).

We'll also need a corresponding Intern update to actually make use of this functionality. Actually, the range handling code might make more sense in Intern than in Dig Dug. Basically, `lib/util.flattenEnvironments` should accept a Tunnel object, and should request the available environments from the tunnel. `flattenEnvironments` can either get the whole list and figure out which specific versions to use itself, or the tunnel can handle environment flattening. In either case, the Tunnel should given Intern a list of environments, where each entry has the standardized form of:

```js
{
	browserName: browserName,
	version: browserVersion,
	platform: platformName,
	platformVersion: platformVersion
}
```

**Comment by devpaul** [comment]
I like the idea of normalizing the data returned from `getEnvironments()`. However, platforms are inherently non-standard. For instance, how would you recommend we handle [TestingBot's API](https://api.testingbot.com/v1/browsers), which do not return a platform version? SauceLabs is a little more regular, but their platform and version information is combined in a single string and isn't completely normalized either (e.g. "Windows 2000 RC").

**Comment by jason0x43** [comment]
Versions in TestingBot are also returned as part of the platform (Capitan vs. Mavericks, Vista vs. Win8), and even for BrowserStack it's common to specify a platform through the standard Selenium `platform` property, like "WIN8",  rather than using the BS-specific `os` and `os_version` properties. So I suppose the version block could get by with just browserName, version, and platform.

If we were actually doing name normalization, the specific tunnel classes themselves could handle mapping between their specific names and any standard set of names Dig Dug understood. So Intern would pass the Tunnel a list of desired environments, using tunnel-specific names or some standardized set. The tunnel would consider what was requested and what it had available, and then hand back a set of matching environment descriptors to Intern. At that point it's not important what names are being used; Intern will take whatever flattened environments it's given and construct suites based on them.

The thought for name normalization was simply to provide a set of standard platform and browser names that work across platforms (including normal Selenium), and simply pass through any other values. So now we have "Windows 10" on Sauce, "WINDOWS" on BrowserStack, and "WIN10" on TestingBot. It'd be neat if you could just use "Windows 10" and have that work for all of them (similarly with "chrome" on Sauce and BS vs "googlechrome" on TestingBot). We wouldn't need to cover every case; if Dig Dug saw a standard name, it would map it to the service-specific value, otherwise it would just use it as-is.

**Comment by jason0x43** [comment]
Merged in https://github.com/theintern/digdug/commit/96aa488a631f608c14c1a3c337bc048bc8099bd9

**Pull request closed without merging**
